### PR TITLE
Adding free format form & research from Error

### PR DESCRIPTION
**Pull request by peterkwells**
Adding embed form and links

### CODE REVIEW

**Comment by peterkwells** [comment]
@pezholio 

This is the Error Creative stuff getting ready to go up tomorrow

When adding in the report (as a blogpost and 2 images) my local instance starts up ok but none of the site will display. Error message below. Can you have a quick look?

----
undefined method `delete_if' for nil:NilClass

Rails.root: /Users/70a/Documents/Open Addresses/oa site/theodolite

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"path"=>"main"}

---

**Comment by pezholio** [comment]
Hmmmm... That's odd. Seems to work fine for me. Can you try restarting it? (ctrl + c on the terminal and then `rails server` again)

**Comment by peterkwells** [comment]
Did that, twice, just in case ;-) Will reboot.

**Comment by peterkwells** [comment]
No joy. Here's the log from Terminal:

https://gist.github.com/peterkwells/6e6215fa6ee087247a47

**Comment by pezholio** [comment]
That's really odd. Seems related to the Jekyll-esque thing we have. I don't know too much about it, but @Floppy may be able to help. You haven't made any uncommitted changes have you?

**Comment by peterkwells** [comment]
Found it: https://github.com/OpenAddressesUK/jekylly/issues/2

**Comment by pezholio** [comment]
Ah ha! Weird that it doesn't do it for me

**Comment by peterkwells** [comment]
Random unnamed folders don't sync!

**Comment by pezholio** [comment]
Oooooooooooh I seeeeeeeeeeeee!

**Comment by peterkwells** [comment]
Merging

**Pull request merged**
