### PR TITLE
Partial search

### PR DESCRIPTION
**Pull request by Floppy**
Works fine here - might be missing a few results currently, but that fix will go into mongoid_address_models, and only affects excessively wide searches like "b".

### CODE REVIEW

**Comment by pezholio** [comment]
Think you need to update the version in travis.yml

**Comment by pezholio** [comment]
Ruby version, that is

**Comment by Floppy** [comment]
good point - forgot I did that.

**Comment by Floppy** [comment]
OK, this works now due to some shonky waiting-for-the-indexer in tests

**Pull request merged**
