### PR TITLE
Add metrics to homepage

### PR DESCRIPTION
**Pull request by pezholio**
This can be merged once https://github.com/OpenAddressesUK/metrics-api/pull/1 is merged

### CODE REVIEW

**Comment by pikesley** [comment]
It now does this thanks to CORS in metrics-api. So merge away, I guess...

screenshot 2015-04-24 15 49 42

**Comment by peterkwells** [comment]
Before merging this we should get agreement from @peterkwells or Emma Thwaites

**Comment by pezholio** [comment]
Added the inference count now - so now we have this:

untitled

**Comment by pezholio** [comment]
Is this good to go now?

**Comment by peterkwells** [comment]
Yep

**Pull request merged**
